Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
alphas = np.exp(np.linspace(10, -5, 100))
mse = pd.DataFrame([fit_and_report_mses(linear_model.Lasso(alpha=alpha, max_iter=50000),
                           X_train, X_test, y_train, y_test)
                    for alpha in alphas])
mse["log_alpha"] = -np.log10(alphas)
fig, ax = plt.subplots(figsize=(10,6))
mse.plot(x="log_alpha", y="mse_test", c=colors[0], ax=ax)
mse.plot(x="log_alpha", y="mse_train", c=colors[1], ax=ax)
ax.set_xlabel(r"$-\log(\alpha)$")
ax.set_ylabel("MSE")
ax.get_legend().remove()
ax.annotate("test",(mse.log_alpha[15], mse.mse_test[15]),color=colors[0])
ax.annotate("train",(mse.log_alpha[30], mse.mse_train[30]),color=colors[1])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[17], line 8[0m
[1;32m      6[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m10[39m,[38;5;241m6[39m))
[1;32m      7[0m mse[38;5;241m.[39mplot(x[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlog_alpha[39m[38;5;124m"[39m, y[38;5;241m=[39m[38;5;124m"[39m[38;5;124mmse_test[39m[38;5;124m"[39m, c[38;5;241m=[39mcolors[[38;5;241m0[39m], ax[38;5;241m=[39max)
[0;32m----> 8[0m [43mmse[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mx[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mlog_alpha[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43my[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mmse_train[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mc[49m[38;5;241;43m=[39;49m[43mcolors[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m)[49m
[1;32m      9[0m ax[38;5;241m.[39mset_xlabel([38;5;124mr[39m[38;5;124m"[39m[38;5;124m$-[39m[38;5;124m\[39m[38;5;124mlog([39m[38;5;124m\[39m[38;5;124malpha)$[39m[38;5;124m"[39m)
[1;32m     10[0m ax[38;5;241m.[39mset_ylabel([38;5;124m"[39m[38;5;124mMSE[39m[38;5;124m"[39m)

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_core.py:1000[0m, in [0;36mPlotAccessor.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    997[0m             label_name [38;5;241m=[39m label_kw [38;5;129;01mor[39;00m data[38;5;241m.[39mcolumns
[1;32m    998[0m             data[38;5;241m.[39mcolumns [38;5;241m=[39m label_name
[0;32m-> 1000[0m [38;5;28;01mreturn[39;00m [43mplot_backend[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mkind[49m[38;5;241;43m=[39;49m[43mkind[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/__init__.py:71[0m, in [0;36mplot[0;34m(data, kind, **kwargs)[0m
[1;32m     69[0m         kwargs[[38;5;124m"[39m[38;5;124max[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mgetattr[39m(ax, [38;5;124m"[39m[38;5;124mleft_ax[39m[38;5;124m"[39m, ax)
[1;32m     70[0m plot_obj [38;5;241m=[39m PLOT_CLASSES[kind](data, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m---> 71[0m [43mplot_obj[49m[38;5;241;43m.[39;49m[43mgenerate[49m[43m([49m[43m)[49m
[1;32m     72[0m plot_obj[38;5;241m.[39mdraw()
[1;32m     73[0m [38;5;28;01mreturn[39;00m plot_obj[38;5;241m.[39mresult

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:454[0m, in [0;36mMPLPlot.generate[0;34m(self)[0m
[1;32m    452[0m [38;5;28mself[39m[38;5;241m.[39m_make_plot()
[1;32m    453[0m [38;5;28mself[39m[38;5;241m.[39m_add_table()
[0;32m--> 454[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_legend[49m[43m([49m[43m)[49m
[1;32m    455[0m [38;5;28mself[39m[38;5;241m.[39m_adorn_subplots()
[1;32m    457[0m [38;5;28;01mfor[39;00m ax [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39maxes:

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:792[0m, in [0;36mMPLPlot._make_legend[0;34m(self)[0m
[1;32m    790[0m     title [38;5;241m=[39m leg[38;5;241m.[39mget_title()[38;5;241m.[39mget_text()
[1;32m    791[0m     [38;5;66;03m# Replace leg.LegendHandles because it misses marker info[39;00m
[0;32m--> 792[0m     handles [38;5;241m=[39m [43mleg[49m[38;5;241;43m.[39;49m[43mlegendHandles[49m
[1;32m    793[0m     labels [38;5;241m=[39m [x[38;5;241m.[39mget_text() [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m leg[38;5;241m.[39mget_texts()]
[1;32m    795[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mlegend:

[0;31mAttributeError[0m: 'Legend' object has no attribute 'legendHandles'

